services:
  accounting:
    build: .
    container_name: electronic-money-records
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
